### PR TITLE
Fix rubocop LineLength # see https://rubocop.readthedocs.io/en/latest…

### PR DESCRIPTION
**Pull request by thomas-merz**
…/cops_layout/#layoutlinelength

### CODE REVIEW

**Comment by alexjfisher** [comment]
This is incorrect for the version of rubocop used by this project.  See https://travis-ci.org/github/puppetlabs/puppetlabs-host_core/jobs/670671270#L1413

**Comment by thomasmerz** [comment]
@alexjfisher , @CLAassistant asks me for signing a CLA - but is this really and now necessary after https://github.com/puppetlabs/puppetlabs-host_core/pull/18#issuecomment-623310159 ? Will my PR be merged if I sign this CLA or is this a mistake?

**Comment by thomas-merz** [comment]
@alexjfisher , @CLAassistant asks me for signing a CLA - but is this really and now necessary after https://github.com/puppetlabs/puppetlabs-host_core/pull/18#issuecomment-623310159 ? Will my PR be merged if I sign this CLA or is this a mistake?

**Comment by joshcooper** [comment]
@thomas-merz sorry for the CLA automation spam. I'm fine treating this as trivial, but the module currently pins to [rubycop 0.49.x](https://github.com/puppetlabs/puppetlabs-host_core/blob/main/Gemfile#L24). You should be able to relax the constraint like [puppet does](https://github.com/puppetlabs/puppet/blob/c6412ea369aa1613ca166b10fb819fcf6130814b/Gemfile#L48), so it will match `0.49 >= 0 && < 1.0`

**Comment by thomas-merz** [comment]
@joshcooper , so do we close this PR or what shall we/I do with it? 🤔

**Comment by joshcooper** [comment]
Hi @thomas-merz as @alexjfisher mentioned above, this change is not compatible with the version of rubocop that the module *currently* depends on. If you update the module to use a more recent version of rubocop and update the rubocop config in the same PR that'd be best. Also we have changed our CLA policy since you opened this PR and there isn't a trivial exemption anymore. It'd be great if you'd like to continue, but understand if you want to close.

**Comment by thomasmerz** [comment]
Closing, because "my" change is already in `[main](https://github.com/puppetlabs/puppetlabs-host_core/blob/main/.rubocop.yml#L21)`: `Layout/LineLength` instead of `Metrics/LineLength` 👍🏻

**Comment by thomas-merz** [comment]
Closing, because "my" change is already in [main](https://github.com/puppetlabs/puppetlabs-host_core/blob/main/.rubocop.yml#L21) by https://github.com/puppetlabs/puppetlabs-host_core/commit/e78ecf8948988656bcb83aff2587f1641099416d: `Layout/LineLength` instead of `Metrics/LineLength` 👍🏻

**Pull request closed without merging**
